modLoader="javafml"
loaderVersion="[39,)"
license="MIT"

[[mods]]
modId="rose"
version="1.0"
displayName="Rosé"
logoFile="rose-forge-logo.png"
authors="bmedina"
description="Rose gold armor and tools."

[[dependencies.rose]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rose]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"